[custom.all.go-model]
type = "local"
path = "."
ipkg = "go-model.ipkg"
test = "test/test.ipkg"

# [custom.all.deptycheck]
# type = "github"
# url = "https://github.com/buzden/deptycheck"
# commit = "fetch-latest:master"
# ipkg = "deptycheck.ipkg"
