[custom.all.go-module]
type = "local"
path = "."
ipkg = "go-model.ipkg"
test = "test/test.ipkg"

[custom.all.go-module-test]
type = "local"
path = "test"
ipkg = "test.ipkg"

# [custom.all.deptycheck]
# type = "github"
# url = "https://github.com/buzden/deptycheck"
# commit = "latest:order-experim"
# ipkg = "deptycheck.ipkg"
