---
name: DepTyCheck

on:
  push:
    branches:
      - master
      - 'debug-ci/**'
    tags:
      - '**'
  pull_request:
    branches:
      - main
      - master
  schedule:
    # We want to run in the beginning of the day, right after the `pack` collection is built at the end of the previous day.
    - cron: '0 1 * * *'

permissions: read-all

concurrency:
  group: ${{ github.workflow }}@${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:

  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    container: ghcr.io/stefan-hoeck/idris2-pack:latest
    steps:
      - uses: actions/checkout@v4

      - name: Rebuild from skratch
        run: |
          ./rebuild-from-skratch.sh

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: python ./try_compile.py
